name: Update Token List

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-tokenlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Update Token List
        env:
          SUBGRAPH_URL: ${{ secrets.SUBGRAPH_URL }}
        run: node update-tokenlist.js
        
      - name: Configure Git and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/squidswap-ink/ss-token-list.git
          git add tokenlist.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update token list"
          git push